### ISSUE TITLE
kanban board for open issues

### ISSUE THREAD

**Issue by rossry** [CAVaccineInventory/vaccine-feed-ingest#203]
I made a quick-and-dirty kanban board to visualize the open+unblocked runner (fetch/parse/normalize) issues, open to the public [here](https://docs.google.com/spreadsheets/d/1vpZ5uXWrVodJQVj-CLQE4Na8YF_rvn8o6cdvbk4e7UM/edit?usp=sharing). Does it make sense to edit this (edit: or something other way of tracking available issues) into the wiki's description of how to find an issue to help with?

**Comment by ericrobinsondev** [comment]
Not sure if it would be helpful, but you can do project boards directly in github.

**Comment by eliblock** [comment]
Hi @rossry - thank you for pulling this together!

We're working on our overall issue tracking internally (we have _many_ more sites we plan to open issues to fetch/parse/normalize over the coming weeks), and will certainly keep in mind that we need to make it easier to discover issues which need contributions, and avoid conflicting with other contributors! (CC: @tmb)

At this point I'm going to hold off on adding this board to the wiki because we're still working out that process, but if it looks like this is still needed in a week or so, we can definitely reconsider!

**Comment by rossry** [comment]
@eliblock -- that makes sense to me. Thanks!
