### ISSUE TITLE
parse immunizenevada_org from NV

### ISSUE THREAD

**Issue by eliblock** [CAVaccineInventory/vaccine-feed-ingest#92]
[![learn our pipeline: parse](https://img.shields.io/static/v1?label=learn%20our%20pipeline&message=parse&style=social)](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#parse)

Blocked by #91 

Parse existing data into [`.ndjson`](http://ndjson.org/).

Read all files in the directory passed as the second argument (`sys.argv[2]`), convert them to `.ndjson`, and then output them to new files in the directory passed as the first argument (`sys.argv[1]`).

Check the wiki to learn more about the purpose of the parse stage and how to get set up for development!

### Tips

1. Fetch data for this site before you start developing:
    ```sh
    poetry run vaccine-feed-ingest fetch nv/immunizenevada_org
    ```

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest parse nv/immunizenevada_org
    ```

### Example
[Fetched files for `md/arcgis`](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/md/arcgis/raw) are converted to [parsed files](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/md/arcgis/parsed)

**Comment by toffer** [comment]
I'll take this.

**Comment by toffer** [comment]
@eliblock To write the parser, I'm building on the fetcher that @cdjj added here: https://github.com/CAVaccineInventory/vaccine-feed-ingest/pull/132.

The JSON returned from the fetcher looks like this: https://gist.github.com/toffer/5ad378f2edfaa03b67012c005dd4847b

While the fetched JSON does contain a list of objects, it doesn't make sense to me to do a straightforward conversion of that to a `.ndjson` file. Most of the lines would be useless, since all of the important data is in a single HTML snippet inside the `data` field of one of the objects (https://gist.github.com/toffer/5ad378f2edfaa03b67012c005dd4847b#file-nv-json-L716). 

I'm thinking that the right approach is to:

1. Grab the HTML snippet out of the JSON.
2. Parse the HTML.
3. Return newline-delimited JSON objects.

The output would look something like this:

```
{"title": "Albertsons #1059", "url": "https://www.mhealthappointments.com/covidappt", "address": "5500 Boulder Hwy, Las Vegas, NV, 89122", "contact-phone": "(702) 435-7339", "lat": "36.01851325", "lng": "-115.2649152"}
{"title": "Albertsons #118", "url": "https://www.mhealthappointments.com/covidappt", "address": "7151 W Craig Rd, Las Vegas, NV, 89129", "contact-phone": "(702) 839-9256", "lat": "36.05488226", "lng": "-115.2414274"}
...
```

Does this seem like the right approach to you?

**Comment by cdjj** [comment]
FWIW, I strongly suspect there's a way to get better data (i.e. JSON, not a JSON-HTML-JSON encapsulation) out of the site, but I couldn't hit on the right combination of parameters to get that to work.
